#####################################
##                                 ##
##            MESSAGES             ##
##                                 ##
#####################################

firstjoins: 154

format:
  join: '<prefix><player> &3has connected to the lobby.'
  quit: '<prefix><player> &3has left the lobby.'
  chat: '<prefix><player>&7: &f<message> '
  firstjoin: '&b<player> &7has joined the lobby for the first time! &3[#[UNIQUE]]'

#####################################
##                                 ##
##           PERMISSIONS           ##
##                                 ##
#####################################

Permission:
  message: '&cInsufficient Permissions!'
Lobby:
  Join: 'Lobby.join'
  Build: 'Lobby.build'
  Interact: 'Lobby.interact'
  Command:
    setspawn: 'Lobby.command.setspawn'
    elytra: 'Lobby.command.elytra'
    event: 'Lobby.command.event'


#####################################
##                                 ##
##              MISC               ##
##                                 ##
#####################################

Event: '100VSMINI'

Spawn:
  X: -12.0
  Y: 40.0
  Z: 33.0
  Pitch: 0.0
  Yaw: 0.0

Pvp:
  All: false
  Player: true
