name: Lobby
main: org.Nokwok.Main
author: Mattq
version: 1.0
api-version: 1.13

commands:
  spawn:
    description: Spawn!
  elytra:
    description: Swoosh!
    aliases: [ely, elytra]
  event:
    description: Event